---

# This is the hosts file. It is in YAML format and contains 
# the IP address and credentials of each router on the network
routers:
  hosts:
    R1:
      ansible_host: 172.168.1.17
    R2:
      ansible_host: 192.168.2.2
    R3:
      ansible_host: 192.168.4.2
    R4:
      ansible_host: 192.168.6.2

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: cisco
    ansible_ssh_pass: cisco
    ansible_action_warnings: False

